### PR TITLE
Website UI Improvement

### PR DESCRIPTION
**Pull request by Nivedita967**
Have proposed these changes-
1. Added toggle dark mode/ light mode button.
2. Added Back to top button.
3. Adjustment of images.

Let me know if any changes required.

Screenshot (178)

Screenshot (179)

Screenshot (177)

### CODE REVIEW

**Comment by virejdasani** [comment]
@Nivedita967, thanks a lot for contributing, this looks awesome. Just a couple of things:
- When toggling dark/light mode, the green-blue gradient background gets inverted. Can you make it so that it stays the same
- Also, the background color is too dark, it would look better if you change the black to `#232323`

**Comment by Nivedita967** [comment]
> @Nivedita967, thanks a lot for contributing, this looks awesome. Just a couple of things:
> 
> * When toggling dark/light mode, the green-blue gradient background gets inverted. Can you make it so that it stays the same
> * Also, the background color is too dark, it would look better if you change the black to `#232323`
> * Lastly, can you move all the JavaScript in a separate `index.js` or `main.js` file

Sure.

**Comment by Nivedita967** [comment]
Please review. Is it okay?

Screenshot (180)

**Comment by virejdasani** [comment]
Looks good, going ahead with the merge :)

**Pull request merged**
