### PR TITLE
Add `https://` to URL when the inputted URL is without `https://`

### PR DESCRIPTION
**Pull request by kazuhitonakayama**
## Issue
#7 

## Overview
Add `https://` to URL only when the inputted URL is without `https://`

## Intention
It would be easier to search if you could just enter the URL of the domain only.

### CODE REVIEW

**Comment by kazuhitonakayama** [comment]
I hope you will review it when you have time! :)
@virejdasani

**Comment by virejdasani** [comment]
Hi @kazuhitonakayama, this looks awesome! When reviewing I noticed that although the website that gets loaded has the `https://`

 prefix, the url input box stays without the `https://`

Screenshot 2021-09-02 at 8 15 37 AM


If you add this line:
```js
document.querySelector("#urlInput").value = website
```
in the `goButton.addEventListener`, under this:
```js
normalizedUrl = normalizeUrl(inputtedUrl);
website = normalizedUrl;
```
Then the `https://` will automatically get added to the search bar :)

Screenshot 2021-09-02 at 8 16 33 AM

**Comment by kazuhitonakayama** [comment]
@virejdasani 
Oh, sorry I missed it .. :(
I will fix it !
Thank you for your review :)

**Comment by kazuhitonakayama** [comment]
@virejdasani 
Hi, I made some changes :)
https://github.com/kazuhitonakayama/Responsivize/commit/937315f3a44c1306650fa214818d8f49a07d8513
https://github.com/kazuhitonakayama/Responsivize/commit/d7e06b69d1791e4f3953cab019416d9f8649c305

I would like you to review this PR when you have time 👍

**Comment by virejdasani** [comment]
Hi @kazuhitonakayama, thanks a lot for contributing! It works perfectly :)

**Comment by kazuhitonakayama** [comment]
Thank you for you to make awesome app, Responsivize:)

**Comment by virejdasani** [comment]
> Thank you for you to make awesome app, Responsivize:)

I'm glad you liked it!

**Pull request merged**
